version: '3.1'

services:
  postgres:
    image: postgres:13.3
    container_name: postgressdb
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    ports:
      - 5432:5432
    env_file: .env

  pgadmin:
    image: dpage/pgadmin4:7.8
    container_name: pgadmindb
    env_file: .env
    ports:
      - 5050:80
    depends_on:
      - postgres

volumes:
  db_data: